sudo: required
language: lua
services:
  - docker
before_install:
  - docker build -t travis_build ./
script:
  - docker run -v `pwd`:/gateway travis_build prove
  - docker run -v `pwd`:/gateway travis_build busted  
